services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-exchange-app
    volumes:
      - .:/var/www
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./storage/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mini_exchange
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: 'secret;2025'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: